modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TaoLe-si/MC-Thread/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/TaoLe-si/MC-Thread"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="threadtearer"
    type="required"
    versionRange="[0.3.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="immersiveengineering"
    type="required"
    versionRange="[12.4.0,)"
    ordering="AFTER"
    side="BOTH"